{% set name = "fsl-pipe-gui" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1c1f857a745fbd27a4a7c7dc65d25780bc3c9bc3ef420ee27ed9ddaa1dae85aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - fsl-pipe >=0.7
    - file-tree
    - textual >=0.29

test:
  imports:
    - fsl_pipe_gui
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.fmrib.ox.ac.uk/ndcn0236/fsl-pipe-gui
  summary: Terminal-based GUI for fsl-pipe
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichielCottaar
